# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: armando
  pool: 5
  username: root
  password: 12345678
  socket: 3306

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: armando
  pool: 5
  username: root
  password: 12345678
  socket:  3306

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: armando
  pool: 5
  username: root
  password: 12345678
  socket: 3306